In [ ]:
##предварительная обработка текста

In [ ]:
!pip install numpy
!pip install pandas
!pip install nltk
!pip install re

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.6)
ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for re

In [ ]:
import numpy as np
import pandas as pd
import re
import nltk
import string

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#help(pd.read_csv)

In [ ]:
##Чтение датасета с текстом
#df = pd.read_csv("/reviews.csv", encoding='UTF8', sep="\t")
df = pd.read_csv("hf://datasets/data-silence/lenta.ru_2-extended/final_lenta_new.csv.gz", nrows = 69001)
df = df.drop(columns=['news', 'url', 'links', 'topic', 'date'])
df.head(10)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

                                               title             tags
0    В Курской области объявили опасность атаки БПЛА     Происшествия
1  Юристы прокомментировали иск пострадавших в от...  Следствие и суд
2  На Западе рассказали о нехватке Patriot для пе...         Политика
3  Очередные российские спортсмены отказались от ...      Летние виды
4  Байден и Си Цзиньпин обсудили ситуацию вокруг ...         Политика
5  Последствия мощного землетрясения на Тайване п...     Происшествия
6  Родственникам погибших в «Крокусе»  назначили ...         Общество
7  Цунами достигло японского острова после землет...     Происшествия
8  На Украине заявили об ужесточении мобилизации ...          Украина
9  Британия осудила Северную Корею из-за пуска ба...         Политика

In [ ]:
df.iloc[[1]]
df.tail(3)
#df['review'][0:10]

                                                   title      tags
68998               ВСУ обстреляли Донецк из РСЗО «Град»   Украина
68999  Сыгравший Гэндальфа актер пообещал пранкерам п...  Интернет
69000        Михалков и Лепс попали под новые санкции ЕС      Кино

In [ ]:
##Нижний регистр. Например, Товар --> товар, УРА --> ура
df['text_lower']  = df['title'].str.lower()
df['text_lower'].head()

0      в курской области объявили опасность атаки бпла
1    юристы прокомментировали иск пострадавших в от...
2    на западе рассказали о нехватке patriot для пе...
3    очередные российские спортсмены отказались от ...
4    байден и си цзиньпин обсудили ситуацию вокруг ...
Name: text_lower, dtype: object

In [ ]:
df.head()

,title,tags,text_lower
0,В Курской области объявили опасность атаки БПЛА,Происшествия,в курской области объявили опасность атаки бпла
1,Юристы прокомментировали иск пострадавших в от...,Следствие и суд,юристы прокомментировали иск пострадавших в от...
2,На Западе рассказали о нехватке Patriot для пе...,Политика,на западе рассказали о нехватке patriot для пе...
3,Очередные российские спортсмены отказались от ...,Летние виды,очередные российские спортсмены отказались от ...
4,Байден и Си Цзиньпин обсудили ситуацию вокруг ...,Политика,байден и си цзиньпин обсудили ситуацию вокруг ...

In [ ]:
#Удаление пунктуации
df['text_punct'] = df['text_lower'].str.replace('[{}]'.format(string.punctuation), '', regex=True)
df['text_punct'] = df['text_punct'].str.replace('[^\w\s]', '', regex=True)
df['text_punct'] = df['text_punct'].str.replace("\d", "", regex=True)
df['text_punct'].head()

0      в курской области объявили опасность атаки бпла
1    юристы прокомментировали иск пострадавших в от...
2    на западе рассказали о нехватке patriot для пе...
3    очередные российские спортсмены отказались от ...
4    байден и си цзиньпин обсудили ситуацию вокруг ...
Name: text_punct, dtype: object

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
print(stopwords.words('russian'))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
#Удаление стоп-слов
#Импорт стоп-слов из бибилиотеки nltk
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('russian'))
# функция, удаляющая стопслова из текстов

def stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
# Применим функцию удаления стоп-слов
df["text_stop"] = df["text_punct"].apply(stopwords)
df["text_stop"].head()

0        курской области объявили опасность атаки бпла
1    юристы прокомментировали иск пострадавших отно...
2      западе рассказали нехватке patriot передачи всу
3    очередные российские спортсмены отказались уча...
4    байден си цзиньпин обсудили ситуацию вокруг ti...
Name: text_stop, dtype: object

In [ ]:
#Удаление высокочастотных слов
from collections import Counter
cnt = Counter()
for text in df["text_stop"].values:
    for word in text.split():
        cnt[word] += 1

cnt.most_common(10)#[:-n:-1]

[('россии', 8184),
 ('сша', 4109),
 ('украине', 3786),
 ('всу', 3054),
 ('изза', 2483),
 ('украины', 2043),
 ('назвали', 1659),
 ('заявили', 1618),
 ('назвал', 1555),
 ('рассказал', 1492)]

In [ ]:
#ужаление часто встречающиеся слов в корпусе при помощи tf-idf
# Удаление самых частотных слов
freq = set([w for (w, wc) in cnt.most_common(50)])
# функция удаления слов
def freqwords(text):
    return " ".join([word for word in str(text).split() if word not
in freq])
# применение функции
df["text_common"] = df["text_stop"].apply(freqwords)
df["text_common"].head()

0                курской объявили опасность атаки бпла
1    юристы прокомментировали иск пострадавших отно...
2                     западе нехватке patriot передачи
3    очередные спортсмены отказались участия олимпиаде
4    байден си цзиньпин обсудили ситуацию вокруг ti...
Name: text_common, dtype: object

In [ ]:
#Удаление низкочастотных слов
freq = pd.Series(' '.join(df['text_common']).split()).value_counts()[-50:] # 10 rare words
freq = list(freq.index)
df['text_rare'] = df['text_common'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
df['text_rare'].head()

0                курской объявили опасность атаки бпла
1    юристы прокомментировали иск пострадавших отно...
2                     западе нехватке patriot передачи
3    очередные спортсмены отказались участия олимпиаде
4    байден си цзиньпин обсудили ситуацию вокруг ti...
Name: text_rare, dtype: object

In [ ]:
# Удаление эмодзи
def emoji(string):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', string)
#passing the emoji function to 'text_rare'
df['text_rare'] = df['text_rare'].apply(emoji)

In [ ]:
#Удаление цифр
df['text_nonum'] = df['text_common'].str.replace("\d", "", regex=True)
df['text_nonum'].head()

0                курской объявили опасность атаки бпла
1    юристы прокомментировали иск пострадавших отно...
2                     западе нехватке patriot передачи
3    очередные спортсмены отказались участия олимпиаде
4    байден си цзиньпин обсудили ситуацию вокруг ti...
Name: text_nonum, dtype: object

In [ ]:
#Удаление URL
# Function for url's
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)
# Examples
text = "This is my website, https://www.link.com"
remove_urls(text)
#Passing the function to 'text_rare'
df['text_rare'] = df['text_rare'].apply(remove_urls)

In [ ]:
#Удаление HTML-тегов
from bs4 import BeautifulSoup
#Function for removing html
def html(text):
    return BeautifulSoup(text, "lxml").text
# Examples
text = """<div>
<h1> Это </h1>
<p> странца</p>
<a href="https://www.link.com/"> пример</a>
</div>
"""
print(html(text))
# Passing the function to 'text_rare'
df['text_rare'] = df['text_rare'].apply(html)

 Это
 странца
 пример

In [ ]:
#Токенизация
def tokenization(text):
    text = re.split('\W+', text)
    return text
# Passing the function to 'text_rare' and store into'text_token'
df['text_token'] = df['text_rare'].apply(lambda x: tokenization(x.lower()))
df[['text_token']].head()

                                          text_token
0        [курской, объявили, опасность, атаки, бпла]
1  [юристы, прокомментировали, иск, пострадавших,...
2              [западе, нехватке, patriot, передачи]
3  [очередные, спортсмены, отказались, участия, о...
4  [байден, си, цзиньпин, обсудили, ситуацию, вок...

In [ ]:
#Можно выполнить при помощи NLTK. Заодно проведем лемматизацию
!pip install pymorphy2
from pymorphy2 import MorphAnalyzer
from nltk import sent_tokenize, word_tokenize, regexp_tokenize

def tokenize_lemmas(sent, pat=r"(?u)\b\w\w+\b", morph=MorphAnalyzer()):
    return [morph.parse(tok)[0].normal_form
            for tok in regexp_tokenize(sent, pat)]
df["text_lemm"] = df["text_rare"].map(lambda x: " ".join(tokenize_lemmas(x)))
df[['text_lemm']].head()

Collecting pymorphy2
  Downloading pymorphy2-0.9.1-py3-none-any.whl.metadata (3.6 kB)
Collecting dawg-python>=0.7.1 (from pymorphy2)
  Downloading DAWG_Python-0.7.2-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting pymorphy2-dicts-ru<3.0,>=2.4 (from pymorphy2)
  Downloading pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting docopt>=0.6 (from pymorphy2)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Downloading pymorphy2-0.9.1-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 3.2 MB/s eta 0:00:00
Downloading DAWG_Python-0.7.2-py2.py3-none-any.whl (11 kB)
Downloading pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 73.0 MB/s eta 0:00:00
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=f3b66eaf53a839867c5270115cb13ebf765f9543dc64168bed1ee807b2a0c456
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built docopt
Installing collected packages: pymorphy2-dicts-ru, docopt, dawg-python, pymorphy2
Successfully installed dawg-python-0.7.2 docopt-0.6.2 pymorphy2-0.9.1 pymorphy2-dicts-ru-2.4.417127.4579844

                                           text_lemm
0            курский объявить опасность атака бпнуть
1  юрист прокомментировать иск пострадать отношен...
2                    запад нехватка patriot передача
3   очередной спортсмен отказаться участие олимпиада
4  байден си цзиньпин обсудить ситуация вокруг ti...

In [ ]:
#Исходя из цели автоматической обработки текста, выберем необходимые варианты предобработки текста.
#Например, для классификации можно воспользоваться нижним регистром, удалением  пунктуации, ссылок, стоп-слов,
#произвести лемматизацию и токенизацию
##ИЛИ воспользоваться только удалением ссылок. Т.к. это актуальнее для НС, а выбор предобработки сделал для Машинного обученя
df['text_ready']  = df['title'].str.lower()
df['text_ready'] = df['text_ready'].str.replace('\d+', '')
df['text_ready'] = df['text_ready'].str.replace('[^\w\s]','')
df["text_ready"] = df["text_ready"].apply(stopwords)
df['text_ready'] = df['text_ready'].apply(emoji)
df['text_ready'] = df['text_ready'].apply(remove_urls)
df['text_ready'] = df['text_ready'].apply(html)
df["text_ready"] = df["text_ready"].map(lambda x: " ".join(tokenize_lemmas(x)))
df[['text_ready']].head()
df.to_csv('/content/drive/MyDrive/preprocessed_lenta_titles.csv')
df.tail(3)

<ipython-input-17-bbaa63d029ab>:5: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  return BeautifulSoup(text, "lxml").text

,title,tags,text_lower,text_punct,text_stop,text_common,text_rare,text_nonum,text_token,text_lemm,text_ready
68998,ВСУ обстреляли Донецк из РСЗО «Град»,Украина,всу обстреляли донецк из рсзо «град»,всу обстреляли донецк из рсзо град,всу обстреляли донецк рсзо град,обстреляли донецк рсзо град,обстреляли донецк рсзо град,обстреляли донецк рсзо град,"[обстреляли, донецк, рсзо, град]",обстрелять донецк рсзый град,всу обстрелять донецк рсзый град
68999,Сыгравший Гэндальфа актер пообещал пранкерам п...,Интернет,сыгравший гэндальфа актер пообещал пранкерам п...,сыгравший гэндальфа актер пообещал пранкерам п...,сыгравший гэндальфа актер пообещал пранкерам п...,сыгравший гэндальфа актер пообещал пранкерам п...,сыгравший гэндальфа актер пообещал пранкерам п...,сыгравший гэндальфа актер пообещал пранкерам п...,"[сыгравший, гэндальфа, актер, пообещал, пранке...",сыграть гэндальф актёр пообещать пранкер приех...,сыграть гэндальф актёр пообещать пранкер приех...
69000,Михалков и Лепс попали под новые санкции ЕС,Кино,михалков и лепс попали под новые санкции ес,михалков и лепс попали под новые санкции ес,михалков лепс попали новые санкции ес,михалков лепс попали новые санкции,михалков лепс попали новые санкции,михалков лепс попали новые санкции,"[михалков, лепс, попали, новые, санкции]",михалков лепс попасть новый санкция,михалков лепс попасть новый санкция ес

In [ ]:
##Пример препобученной модели HuggingFace Torch

In [ ]:
import torch
from transformers import AutoModelForSequenceClassification
from transformers import BertTokenizerFast

tokenizer = BertTokenizerFast.from_pretrained('blanchefort/rubert-base-cased-sentiment')
model = AutoModelForSequenceClassification.from_pretrained('blanchefort/rubert-base-cased-sentiment', return_dict=True)


def predict(text):
    inputs = tokenizer(text, max_length=512, padding=True, truncation=True, return_tensors='pt')
    outputs = model(**inputs)
    predicted = torch.nn.functional.softmax(outputs.logits, dim=1)
    predicted = torch.argmax(predicted, dim=1).numpy()
    return predicted

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/499 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/1.40M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/943 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/711M [00:00<?, ?B/s]

In [ ]:
#txt = df.iloc[2,2]
txt = "Хм! Очень даже неплохо."
print(txt)

Хм! Очень даже неплохо

In [ ]:
def predict(text):
    inputs = tokenizer(text, max_length=512, padding=True, truncation=True, return_tensors='pt')
    outputs = model(**inputs)
    predicted = torch.nn.functional.softmax(outputs.logits, dim=1)
    predicted = torch.argmax(predicted, dim=1).numpy()
    return predicted

In [ ]:
 predict(txt)

array([1])